---
#    \ \        / (_) |   | |
#    \ \  /\  / / _| | __| | ___ _ __ _ __   ___  ___ ___
#    \ \/  \/ / | | |/ _` |/ _ \ '__| '_ \ / _ \/ __/ __|
#    \  /\  /  | | | (_| |  __/ |  | | | |  __/\__ \__ \
#    \/  \/   |_|_|\__,_|\___|_|  |_| |_|\___||___/___/

# Wilderness World.

WildWorld: "world"

# Teleport coords.

MinCoord: "200"
MaxCoord: "999"

...
